#' Quantile-Quantile plot comparing Rubin's rules with ABpool
#'
#' Generates a Q--Q plot comparing the quantiles from Rubin's
#' t-approximation with posterior samples generated by approximate
#' Bayesian pooling (ABpool).
#'
#' The plot is intended to diagnose potential discrepancies in the
#' distribution given by Rubin's rules by comparing it with the
#' corresponding distribution obtained from ABpool.
#'
#' The quantile probabilities are generated using [ppoints()], in a manner
#' analogous to [qqplot()] and [qqnorm()]. Quantiles from Rubin's t-approximation are
#' plotted on the x-axis and the ABpool posterior samples on the y-axis.
#'
#' @param object An object of class `abpool`, produced by [abpool()].
#' @param parm A character or numeric vector specifying the parameters for which to generate the Q--Q plot.
#'   If `NULL`, a Q--Q plot is generated for every parameter in `object`.
#' @param plot.it Logical. Should the Q--Q plot be plotted? Defaults to `TRUE`.
#' @param add_qqline Logical. Should a Q--Q reference line be added?
#'   Defaults to `TRUE`.
#' @param ... Additional graphical arguments passed to [qqplot()].
#'
#' @return
#' Invisibly returns the following:
#' If `parm` specifies a single parameter, a list containing:
#' \describe{
#'   \item{x}{The quantiles of Rubin's t-approximation at the
#'     probabilities given by `p`. These are the x-coordinates of the
#'     points plotted, or that would be plotted if `plot.it = FALSE`.}
#'   \item{y}{The ABpool posterior samples, sorted in increasing order.
#'     These are the y-coordinates of the points plotted, or that would be
#'     plotted if `plot.it = FALSE`.}
#'   \item{p}{The probabilities used to calculate the quantiles of Rubin's
#'     t-approximation used in the plot, generated using [ppoints()].}
#' }
#'
#' If multiple parameters are specified, a named list containing one such
#' list for each parameter is returned.
#'
#' @details
#' For each parameter, Rubin's t-approximation has location
#' \eqn{
#' \bar{\theta} = \frac{1}{m}\sum_{l=1}^{m}\hat{\theta}^{(l)}
#' }
#' and squared scale
#' \eqn{
#' V = \bar{U} + \left(1 + \frac{1}{m}\right)B,
#' }
#' where \eqn{\bar{U} = \frac{1}{m}\sum_{l=1}^{m}U^{(l)}} is the mean within-imputation variance and \eqn{B=\frac{1}{m}\sum_{l=1}^m (\hat{\theta}^{(l)} - \bar{\theta})^2} is
#' the between-imputation variance.
#' The degrees of freedom are calculated
#' using the Barnard--Rubin method, which simplifies to Rubin's original method
#' when the complete-data degrees of freedom are infinite. The complete-data degrees of freedom are chosen to match those used by ABpool.
#'
#' The resulting t-distribution is compared with the ABpool posterior
#' samples by comparing ordered samples to t-quantiles,
#' with the number of quantiles equal to the number of ABpool samples.
#'
#' @references
#' Phillips DJ, Christodoulou MD and Steinsaltz D. (2026)
#'
#' Barnard, J and Rubin, DB (1999). Small-sample degrees of freedom
#' with multiple imputation. *Biometrika*, 86(4), 948--955.
#'
#' Rubin, DB (1987). *Multiple Imputation for Nonresponse in Surveys*.
#' Wiley.
#'
#' @seealso
#' [abpool()], [qqplot()], [qqline()], [ppoints()], [mice::pool()]
#'
#' @examples
#'
#' # Generate data
#' set.seed(1)
#' n <- 400; nobs <- 40
#' X <- rnorm(n); Z <- sqrt(0.9)*rnorm(n) + sqrt(0.1)*X
#' beta_0 <- 0; beta_X <- 0.8; beta_Z <- 0.2
#' eta <- beta_0 + X*beta_X + Z*beta_Z
#' Y <- rbinom(n, size = 1, p = exp(eta)/(1 + exp(eta)) )
#' X[1:(n-nobs)] <- NA
#' log.data <- data.frame(Y = Y, X = X, Z = Z)
#' m <- 200
#' # Impute using mice (200 imputations, predictive mean matching)
#' imp <- mice::mice(log.data, m = m, method = "pmm", print = FALSE)
#' fits <- with(
#'   imp,
#'   glm(Y ~ X + Z, family = binomial)
#' )
#' # Fit ABpool
#' abpool.out <- abpool(fits)
#' # Compare ABpool and mice in a QQ plot
#' qqplot_rubin_abpool(abpool.out, parm = "X")
#'
#' @export
qqplot_rubin_abpool <- function(object, parm = NULL, plot.it = TRUE, add_qqline = TRUE, ...) {
  # 1. Validate inputs
  # object
  if (!inherits(object,"abpool")){
    stop("`object` must be of class `abpool`. This can be generated by the function `abpool()`.")
  }
  # parm - change to character vector
  parameters <- object$parameters
  if (is.null(parm)){parm <- parameters}
  if (is.numeric(parm)){
    valid_numeric <- all(parm==round(parm)) && all(is.finite(parm)) && all(abs(parm)<=length(parameters)) && (all(parm>0) || all(parm<0))
    if (!valid_numeric){stop("Numeric `parm` must contain non-zero integer indices, either all positive or all negative, whose absolute values are no greater than the number of parameters. Alternatively `parm` may be `NULL`, in which case all parameters will be included, or a character vector of parameter names.")}
    parm <- parameters[parm]
  }
  if (length(parm)==0){stop("No parameters were selected by `parm`.")}
  if (!all(parm %in% parameters)){stop("For `parm` a character vector of parameter names, every element of `parm` must also be an element of `object$parameters`, the parameters in the ABpool sample. Otherwise `parm` may be `NULL`, in which case all parameters will be used, or a numeric vector giving indices of `object$parameters` to output.")}
  # Graphical parameter defaults
  dots <- list(...)
  if (!"xlab" %in% names(dots)) dots$xlab <- "Quantiles from Rubin's t-approximation"
  if (!"ylab" %in% names(dots)) dots$ylab <- "Posterior samples from ABpool"
  main_supplied <- "main" %in% names(dots)
  if (!main_supplied) {
    dots$main <- "Q-Q plot comparing Rubin's rules to ABpool"
  }
  # plot.it, add_qqline
  if(!is.logical(plot.it) || length(plot.it) != 1L){stop("`plot.it` must be a logical (TRUE/FALSE).")}
  if(!is.logical(add_qqline) || length(add_qqline) != 1L){stop("`add_qqline` must be a logical (TRUE/FALSE).")}

  # 2. Extract quantities needed to apply Rubin's rules from `object`
  m <- object$m; dfcom <- object$dfcom; estimates <- object$estimates; variances <- object$variances; samples <- object$samples

  # 3. Apply Rubin's rules
  # Scalar case
  if (is.numeric(estimates)){
    estimate <- mean(estimates)
    ubar <- mean(variances)
    b <- var(estimates)
    v <- ubar + (1 + 1/m)*b
    lambda <- (1 + 1/m)*b/v
    if (dfcom == Inf){
      df <- (m-1)/lambda^2
    } else {
      df_factor <- (1-lambda) * dfcom * (dfcom + 1)
      df <- (m-1) * df_factor / ((m-1) * (dfcom + 3) + lambda^2 * df_factor)
    }
    # Number of samples
    k <- length(samples)
    # Probabilities
    p <- ppoints(k)
    q_rubin <- estimate + qt(p,df) * sqrt(v)
    ordered_samples <- samples[order(samples)]
    if (plot.it){
      do.call(qqplot,c(list(x = q_rubin, y = ordered_samples), dots))
      if (add_qqline){
        qqline(y = ordered_samples, distribution = function(p) estimate + qt(p,df) * sqrt(v))
      }
    }
    return(invisible(list(x = q_rubin, y = ordered_samples, p = p)))
  } else { # Multivariate case
    out <- vector("list", length(parm))
    names(out) <- parm
    # Number of samples
    k <- nrow(samples)
    # Probabilities
    p <- ppoints(k)

    for (parameter in parm) {
      # Extract estimates and variances for parameter
      estimates_parameter <- sapply(estimates, function(x) x[parameter])
      variances_parameter <- sapply(variances, function(x) x[parameter,parameter])
      samples_parameter <- samples[,parameter]
      # Estimate Rubin's rules
      estimate <- mean(estimates_parameter)
      ubar <- mean(variances_parameter)
      b <- var(estimates_parameter)
      v <- ubar + (1 + 1/m)*b
      lambda <- (1 + 1/m)*b/v
      if (dfcom == Inf){
        df <- (m-1)/lambda^2
      } else {
        df_factor <- (1-lambda) * dfcom * (dfcom + 1)
        df <- (m-1) * df_factor / ((m-1) * (dfcom + 3) + lambda^2 * df_factor)
      }
      q_rubin <- estimate + qt(p,df) * sqrt(v)
      ordered_samples <- samples_parameter[order(samples_parameter)]
      if (!main_supplied) {dots$main <- paste0("Q-Q plot",": ",parameter)}
      if (plot.it){
        do.call(qqplot,c(list(x = q_rubin, y = ordered_samples), dots))
        if (add_qqline){
          qqline(y = ordered_samples, distribution = function(p) estimate + qt(p,df) * sqrt(v))
        }
      }
      out[[parameter]] <- list(x = q_rubin, y = ordered_samples, p = p)
    }
    if (length(out)==1) out <- out[[1]] # If only one element in parm, return list without parameter sublist.
    return(invisible(out))
  }
}
